#pragma config(Sensor, S1,     C1,             sensorEV3_Color)
#pragma config(Sensor, S2,     C2,             sensorEV3_Color)
#pragma config(Sensor, S3,     SenColorI,      sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     SenColorD,      sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,          WA,            tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          WB,            tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	int VELW = 100;
	int SI = 0;
	int SD = 0;
	int LRD = 0;
	int LGD = 0;
	int LBD = 0;
	int LRI = 0;
	int LGI = 0;
	int LBI = 0;



	while(true){
		SI = getColorReflected(S1);
		SD = getColorReflected(S2);
		if ((SD >= 20 && SD <=15) || (SI >= 20 && SI <=15)){//pregunta si algun sensor detecta verde//

			//detecta verde Izq y Der//
			if (SI >= 20 && SI <=15){
				getColorRawRGB(SenColorI, LRI,LGI,LBI);
				if (LGI < 30){
					setMotorSyncTime(WA, WB, 50, 1500, VELW);
				}
				}else if(SD >= 20 && SD <=15){
				getColorRawRGB(SenColorD, LRD,LGD,LBD);
				if (LGD < 30){
					setMotorSyncTime(WA, WB, -50, 1500, VELW);
				}
				}else if ((SD >= 20 && SD <=15) && (SD >= 20 && SD <=15)){

				getColorRawRGB(SenColorI, LRI,LGI,LBI);
				getColorRawRGB(SenColorD, LRD,LGD,LBD);

				if(LGD < 30 && LGI < 30){
					setMotorSyncTime(WA, WB, -100, 2500, VELW);
				}
			}
			}else{

			//Detecta Negro Izq y Der//
			if (SD >55){

				//	setMotorSpeed(WB,0);
				setMotorSpeed(WA, VELW );
			}

			else{
				setMotorSpeed(WA,-VELW );
		   	}

			if (SI >=55){

				setMotorSpeed(WB,VELW );
				//setMotorSpeed(WA,0 );
			  }

			else{
				setMotorSpeed(WB,-VELW );
		   	}


		}
	}
}
