#pragma config(Sensor, S1,     C1,             sensorEV3_Color)
#pragma config(Sensor, S2,     C2,             sensorEV3_Color)
#pragma config(Sensor, S3,     SenColorI,      sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     SenColorD,      sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,          WA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          WB,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int VELW = 20;
	int SenNegroI = getColorReflected(C1);
	int SenNegroD = getColorReflected(C2);
	int LR = 0;
	int LG = 0;
	int LB = 0;

	while(true){
		//Detecta Negro Izq y Der//
		if (SenNegroI <=50 && SenNegroD >=50){
			setMotorSpeed(WA, 0);
			setMotorSpeed(WB, VELW);
		}
		if (SenNegroI >=50 && SenNegroD <=50){
			setMotorSpeed(WA, VELW);
			setMotorSpeed(WB, 0);
		}
		//detecta verde Izq y Der//
		if (SenNegroI >= 60 && SenNegroI <=65){
			getColorRawRGB(SenColorI, LR,LG,LB);
			if (LG < 30){
				setMotorSync(WA,WB, 50,VELW);
			}
			}else if(SenNegroD >= 60 && SenNegroD <=65){
			getColorRawRGB(SenColorD, LR,LG,LB);
			if (LG < 30){
				setMotorSync(WA,WB,-50,VELW);
			}
		}

	}

}
