#pragma config(Sensor, S1,     MSLSA,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorB,          MB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lightsensorarray.h";

task main()
{



}
