#pragma config(Sensor, S1,     Sensor_1,       sensorEV3_Color)
#pragma config(Sensor, S2,     Sensor_2,       sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorA,          MB,            tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          MC,            tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Sensor1 = 0;
	int Sensor2 = 0;
	int controlLineaNegra = 0;
	//int velocidadMotores = 20;
	while(true){
		Sensor1 = getColorReflected(Sensor_1);
		Sensor2 = getColorReflected(Sensor_2);

		controlLineaNegra = (((Sensor1 - Sensor2)/2)+6)*1.6/15;
		switch (controlLineaNegra)
		{
		case 3:
			displayBigTextLine(1, "Caso -> 3");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores);
			//setMotorSpeed(MC, -velocidadMotores);
			break;
		case 2:
			displayBigTextLine(1, "Caso -> 2");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores*2.5);
			//setMotorSpeed(MC, velocidadMotores/2);
			break;
		case 1:
			displayBigTextLine(1, "Caso -> 1");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores*1.5);
			//setMotorSpeed(MC, velocidadMotores/1.2);
			break;
		case 0:
			displayBigTextLine(1, "Caso -> 0");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores);
			//setMotorSpeed(MC, velocidadMotores);
			break;
		case -1:
			displayBigTextLine(1, "Caso -> -1");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores/1.2);
			//setMotorSpeed(MC, velocidadMotores*1.5);
			break;
		case -2:
			displayBigTextLine(1, "Caso -> -2");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, velocidadMotores/2);
			//setMotorSpeed(MC, velocidadMotores*2.5);
			break;
		case -3:
			displayBigTextLine(1, "Caso -> -3");
			displayBigTextLine(3, "IZQ: %d", Sensor1);
			displayBigTextLine(5, "DER: %d", Sensor2);
			//setMotorSpeed(MB, -velocidadMotores);
			//setMotorSpeed(MC, velocidadMotores);
			break;
		}


	}


}
