#pragma config(Sensor, S1,     Sensor_1,       sensorEV3_Color)
#pragma config(Sensor, S2,     Sensor_2,       sensorEV3_Color)
#pragma config(Motor,  motorA,          MB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          MC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Sensor1 = 0;
	int Sensor2 = 0;
	int controlLineaNegra = 0;
	int velocidadMotores = 20;
	while(true){

		Sensor1 = getColorReflected(Sensor_1);
		Sensor2 = getColorReflected(Sensor_2);

	controlLineaNegra = round((((Sensor1 - Sensor2)/2)+8)*1.6/15);

	if(controlLineaNegra >= 4){controlLineaNegra = 3;}
	if(controlLineaNegra <= -4){controlLineaNegra = -3;}

	switch (controlLineaNegra)
	{
	case 3:
		setMotorSpeed(motorIzquierdo, 54);
		setMotorSpeed(motorDerecho, -54);
		break;
	case 2:
		setMotorSpeed(motorIzquierdo, 36);
		setMotorSpeed(motorDerecho, -36);
		break;
	case 1:
		setMotorSpeed(motorIzquierdo, 18);
		setMotorSpeed(motorDerecho, -18);
		break;
	case 0:
		setMotorSpeed(motorIzquierdo, 25);
		setMotorSpeed(motorDerecho, 25);
		break;
	case -1:
		setMotorSpeed(motorIzquierdo, -18);
		setMotorSpeed(motorDerecho, 18);
		break;
	case -2:
		setMotorSpeed(motorIzquierdo, -36);
		setMotorSpeed(motorDerecho, 36);
		break;
	case -3:
		setMotorSpeed(motorIzquierdo, -54);
		setMotorSpeed(motorDerecho, 54);
		break;
	}


	}


}
