#pragma config(Sensor, S1,     MSLSA,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorB,          MB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lightsensorarray.h"

task main()
{
	tByteArray signalstr;
	MSLSAinit(MSLSA);

	//writeDebugStreamLine("Type: %d, mode: %d", SensorType[MSLSA], SensorMode[MSLSA]);

	short n = 0;
	int controlLineaNegra = 0;
	int velocidadMotores = 20;
	short valorReflejado[8];

	while(true){

		//MSLSAreadSensors(MSLSA, &signalstr[0]);
    if (!MSLSAreadSensors(MSLSA, &signalstr[0]))
    {
	    for (short i = 0; i < 7; i+=2) {
	      //displayTextLine(i/2+3, "S: %3d S: %3d", (short)signalstr[i], (short)signalstr[i+1]);
	    	valorReflejado[n] = (short)signalstr[i];
	    	n++;
	    }

	    if(valorReflejado[0] == 100 && valorReflejado[1] == 100 && valorReflejado[2] == 100 && valorReflejado[3] == 100
	    	&& valorReflejado[4] == 100 && valorReflejado[5] == 100 && valorReflejado[6] == 100 && valorReflejado[7] == 100){
	    	displayTextLine(3, "Sensores Sobre Blanco");
	    }else if(valorReflejado[0] == 100 && valorReflejado[1] == 100 && valorReflejado[2] == 90 && valorReflejado[3] == 10
	    	&& valorReflejado[4] == 10 && valorReflejado[5] == 90 && valorReflejado[6] == 100 && valorReflejado[7] == 100){
	    	displayTextLine(3, "Linea Negra Centrada");
	    }

	    //TRABAJANDO CON DOS SENSORES DEL CENTRO -> LightSensorArray
	    /*
	    controlLineaNegra = (((valorReflejado[3] - valorReflejado[4])/2)+6)/15;
	    switch (controlLineaNegra)
      {
      case 3:
        setMotorSpeed(MB, velocidadMotores);
        setMotorSpeed(MC, velocidadMotores/2.5);
        break;
      case 2:
        setMotorSpeed(MB, velocidadMotores);
        setMotorSpeed(MC, velocidadMotores/2);
        break;
      case 1:
        setMotorSpeed(MB, velocidadMotores);
        setMotorSpeed(MC, velocidadMotores/1.5);
        break;
      case 0:
        setMotorSpeed(MB, velocidadMotores);
        setMotorSpeed(MC, velocidadMotores);
        break;
      case -1:
        setMotorSpeed(MB, velocidadMotores/1.5);
        setMotorSpeed(MC, velocidadMotores);
        break;
      case -2:
        setMotorSpeed(MB, velocidadMotores/2);
        setMotorSpeed(MC, velocidadMotores);
        break;
      case -3:
        setMotorSpeed(MB, velocidadMotores/2.5);
        setMotorSpeed(MC, velocidadMotores);
        break;
      }
      */

    }

	}


}
