#pragma config(Sensor, S3,     Sen3,           sensorEV3_Color)
#pragma config(Motor,  motorB,          B,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Kd = 1.15  Ki = 0.0003//
//http://www.carlospes.com/curso_de_lenguaje_c/03_02_repetitiva_hacer_mientras.php//
task main()
{

	float Kp = 0.6;
  float Ki = 0;
	float Kd = 0;
	int powerB = 0;
	int Offset = 35;
	int Tp = 25;
	int Integral = 0;
	int lastError = 0;
	int Derivative = 0;
	int ligthValue = 0;
	int Error = 0;
	int Turn = 0;
	int powerC = 0;
  int DT = 10;
	while(true){


		ligthValue = getColorReflected(Sen3);
		Error = Offset - ligthValue;
		Integral = Integral + Error;
		Derivative = Error - lastError;
		Turn = (Kp * Error) + (Ki * Integral) + (Kd * Derivative);
		powerB = Tp + Turn;
		powerC = Tp - Turn;
		setMotorSpeed(B, powerB);
		setMotorSpeed(C, powerC);
		Error = lastError;

		wait1Msec(DT);
	}

}
