#pragma config(Sensor, S1,     sensorIzquierdo, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorDerecho,  sensorEV3_Color)
#pragma config(Motor,  motorA,          motorIzquierdo, tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          motorDerecho,  tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int colorSensorIzquierdo(tSensors sIzquierdo){

	int colorIzquierdo = 0;
	int colorBlanco = 0;

	colorIzquierdo = getColorReflected(sIzquierdo);

	//PREGUNTA SI EL SENSOR IZQUIERDO ESTA EN EL BLANCO
	if(colorIzquierdo > 30){ //SE TOMA COMO VALOR DE REFERENCIA EN BLANCO COMO VALOR SUPERIOR AL 30
		colorBlanco = 1;//SE RETORNA 1 -> COLOR BLANCO;
		}else if(colorIzquierdo >= 8 && colorIzquierdo <= 9){
		colorBlanco = 2;//SE RETORNA 2 -> COLOR POSIBLE VERDE;
		}else{
		colorBlanco = 0;//SE RETORNA 0 -> COLOR NEGRO;
	}
	return colorBlanco;
}

int colorSensorDerecho(tSensors sDerecho){

	int colorDerecho = 0;
	int colorBlanco = 0;

	colorDerecho = getColorReflected(sDerecho);

	//PREGUNTA SI EL SENSOR DERECHO ESTA EN EL BLANCO
	if(colorDerecho > 30){//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO COMO VALOR SUPERIOR AL 30
		colorBlanco = 1;//SE RETORNA 1 -> COLOR BLANCO;
		}else if(colorDerecho >= 11 && colorDerecho <= 12){
		colorBlanco = 2;//SE RETORNA 2 -> COLOR POSIBLE VERDE;
		}else{
		colorBlanco = 0;//SE RETORNA 0 -> COLOR NEGRO;
	}
	return colorBlanco;
}

int colorRGBSensorIzquierdo(tSensors sIzquierdo){

	//VARIABLES DE CONTROL
	int colorSensor,redChannel,greenChannel,blueChannel = 0;
	//FUNCION QUE GUARDA LOS VALORES RGB EN LAS VARIABLES redChannel - greenChannel - blueChannel
	getColorRGB(sIzquierdo, redChannel, greenChannel, blueChannel);

	//VERIFICA SI LAS VARIABLES TIENEN EL VALOR ESPECIFICADO EN EL RANGO
	//DE VALORES RGB ESPECIFICO PARA CADA COLOR (NEGRO, BLANCO, VERDE)

	if((redChannel >= 4 && redChannel <= 9) && (greenChannel >= 16 && greenChannel <= 20) && (blueChannel >= 9 && blueChannel <= 14)){
		colorSensor = 1;//COLOR NEGRO
	}

	if((redChannel >= 48 && redChannel <= 53) && (greenChannel >= 18 && greenChannel <= 50) && (blueChannel >= 17 && blueChannel <= 19)){
		colorSensor = 2;//COLOR BLANCO
	}

	if((redChannel >= 4 && redChannel <= 7) && (greenChannel >= 2 && greenChannel <= 7) && (blueChannel >= 7 && blueChannel <= 11)){
		colorSensor = 3;//COLOR VERDE
	}

	return colorSensor;

}

int colorRGBSensorDerecho(tSensors sDerecho){

	//VARIABLES DE CONTROL
	int colorSensor,redChannel,greenChannel,blueChannel = 0;
	//FUNCION QUE GUARDA LOS VALORES RGB EN LAS VARIABLES redChannel - greenChannel - blueChannel
	getColorRGB(sDerecho, redChannel, greenChannel, blueChannel);

	//VERIFICA SI LAS VARIABLES TIENEN EL VALOR ESPECIFICADO EN EL RANGO
	//DE VALORES RGB ESPECIFICO PARA CADA COLOR (NEGRO, BLANCO, VERDE)

	if((redChannel >= 6 && redChannel <= 11) && (greenChannel >= 15 && greenChannel <= 19) && (blueChannel >= 2 && blueChannel <= 6)){
		colorSensor = 1;//COLOR NEGRO
	}

	if((redChannel >= 57 && redChannel <= 62) && (greenChannel >= 57 && greenChannel <= 62) && (blueChannel >= 17 && blueChannel <= 18)){
		colorSensor = 2;//COLOR BLANCO
	}

	if((redChannel >= 4 && redChannel <= 8) && (greenChannel >= 4 && greenChannel <= 9) && (blueChannel >= 1 && blueChannel <= 3)){
		colorSensor = 3;//COLOR VERDE
	}

	return colorSensor;
}
task main()
{
	int velocidadAvance = -30;
	int velocidadRetroceso = 50;
	int colorIzq = 0;
	int colorDer = 0;
	int colorIzqRGB = 0;
	int colorDerRGB = 0;


	while(true){

		colorIzq = colorSensorIzquierdo(sensorIzquierdo);
		colorDer = colorSensorDerecho(sensorDerecho);
		//detecta Negro y Blanco
		if(colorIzq == 1 && colorDer == 1){
			setMotorSpeed(motorIzquierdo, velocidadAvance);
			setMotorSpeed(motorDerecho, velocidadAvance);
		}

		if(colorIzq == 0 && colorDer == 0){
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, -velocidadAvance);
			sleep(50);
		}

		if(colorIzq == 0 && colorDer == 1){
			setMotorSpeed(motorIzquierdo, velocidadRetroceso);
			setMotorSpeed(motorDerecho, 0);
		}

		if(colorIzq == 1 && colorDer == 0){
			setMotorSpeed(motorIzquierdo, 0);
			setMotorSpeed(motorDerecho, velocidadRetroceso);
		}
		//detecta verde
		if(colorIzq == 2){
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, -velocidadAvance);
			sleep(50);
			colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo);

			if(colorIzqRGB == 3){
				colorDerRGB = colorRGBSensorDerecho(sensorDerecho);
				// avance unos milimetros
				/*setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
				sleep(200);*/

				if(colorRGBSensorDerecho(sensorDerecho)== 3)
				{ // es doble verde
					setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 0, velocidadAvance);
					sleep(3000);
				}
				else
				{
					setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
					sleep(425);
					setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 0, velocidadAvance);
					sleep(1700);
					setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
					sleep(500);
				}
			}
		}

		if(colorDer == 2){
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, -velocidadAvance);
			sleep(200);
			colorDerRGB = colorRGBSensorDerecho(sensorDerecho);

			// hay que avanzar poquito y verificar si el izquierdo en rbg es verde si es verdadero. Estamos en doble verde sino es solo derecho.
			if(colorDerRGB == 3){

				// avance unos milimetros
				//	setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
				//	sleep(200);
				colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo);

				if(colorRGBSensorIzquierdo(sensorIzquierdo)== 3)
				{ // es doble verde
					setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 0, velocidadAvance);
					sleep(3000);
				}
				else
				{
					setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
					sleep(500);
					setMotorSyncTime(motorIzquierdo, motorDerecho, -100, 0, velocidadAvance);
					sleep(1700);
					setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
					sleep(500);
				}
			}
		}

		if(colorIzq == 2 && colorDer == 2){

			colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo);
			colorDerRGB = colorRGBSensorDerecho(sensorDerecho);

			if(colorIzqRGB == 3 && colorDerRGB == 3){
				//setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
				//sleep(500);
				setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 1000, velocidadAvance);
				sleep(3000);
			}
		}
	}
}
/*
if(colorIzqRGB == 3){
setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 200, velocidadAvance);
setMotorSyncTime(motorIzquierdo, motorDerecho, -100, 500, velocidadAvance);
}

if(colorDerRGB == 3){
setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 200, velocidadAvance);
setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 500, velocidadAvance);
}

if(colorIzqRGB == 3 && colorDerRGB == 3){
setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 200, velocidadAvance);
setMotorSyncTime(motorIzquierdo, motorDerecho, 100, 1000, velocidadAvance);
}
*/
