#pragma config(Sensor, S1,     sensorIzquierdo, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorDerecho,  sensorEV3_Color)
#pragma config(Sensor, S3,     sensorCentro,   sensorEV3_Color)
#pragma config(Sensor, S4,     sensorUItrasonic, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorIzquierdo, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorDerecho,  tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorRescate,  tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//--------------------------------------------------------------FUNCIONES-------------------------------------------------------------------

//RECIBE COMO PARAMETROS EL COLOR REFLEJADO (GRISES) DE AMBOS SENSORES Y VELOCIDAD DE AVANCE Y RETROCESO;
void seguidorLineaNegra(int colorIzqReflected, int colorDerReflected){

	int controlLineaNegra = 0;

	controlLineaNegra = round((((colorIzqReflected - colorDerReflected)/2)+8)*1.6/15);

	if(controlLineaNegra >= 4){controlLineaNegra = 3;}
	if(controlLineaNegra <= -4){controlLineaNegra = -3;}

	switch (controlLineaNegra)
	{
	case 3:
		setMotorSpeed(motorIzquierdo, 54);
		setMotorSpeed(motorDerecho, -54);
		break;
	case 2:
		setMotorSpeed(motorIzquierdo, 36);
		setMotorSpeed(motorDerecho, -36);
		break;
	case 1:
		setMotorSpeed(motorIzquierdo, 18);
		setMotorSpeed(motorDerecho, -18);
		break;
	case 0:
		setMotorSpeed(motorIzquierdo, 25);
		setMotorSpeed(motorDerecho, 25);
		break;
	case -1:
		setMotorSpeed(motorIzquierdo, -18);
		setMotorSpeed(motorDerecho, 18);
		break;
	case -2:
		setMotorSpeed(motorIzquierdo, -36);
		setMotorSpeed(motorDerecho, 36);
		break;
	case -3:
		setMotorSpeed(motorIzquierdo, -54);
		setMotorSpeed(motorDerecho, 54);
		break;
	}

}

int colorSensorIzquierdo(tSensors sIzquierdo, int colorIzquierdo){

	int colorBlanco = 0;

	//PREGUNTA SI EL SENSOR IZQUIERDO ESTA EN EL BLANCO
	//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO
	//COMO VALOR SUPERIOR AL 10
	if(colorIzquierdo > 36)												{colorBlanco = 0;} 		//SE RETORNA 0 -> COLOR BLANCO;
	if(colorIzquierdo >= 21 && colorIzquierdo <= 35){colorBlanco = 2;}	  //SE RETORNA 2 -> COLOR POSIBLE VERDE;
	if(colorIzquierdo >= 1 && colorIzquierdo <= 20){colorBlanco = 1;}		//SE RETORNA 1 -> COLOR NEGRO


	return colorBlanco;
}

int colorSensorDerecho(tSensors sDerecho, int colorDerecho){

	int colorBlanco = 0;

	//PREGUNTA SI EL SENSOR DERECHO ESTA EN EL BLANCO
	//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO
	//COMO VALOR SUPERIOR AL 10
	if(colorDerecho > 46)												{colorBlanco = 0;} 		//SE RETORNA 0 -> COLOR BLANCO;
	if(colorDerecho >= 27 && colorDerecho <= 45){colorBlanco = 2;}	  //SE RETORNA 2 -> COLOR POSIBLE VERDE;
	if(colorDerecho >= 1 && colorDerecho <= 26){colorBlanco = 1;}		//SE RETORNA 1 -> COLOR NEGRO


	return colorBlanco;
}

int colorRGBSensorIzquierdo(tSensors sIzquierdo, int colorIzquierdo){

	int colorSensor = 2;
	int colorHUE = 0;
	int tiempoLectura = 700;

	if(colorIzquierdo < 35){
		while(tiempoLectura > -1){colorHUE = getColorHue(sIzquierdo); tiempoLectura--;}
		if(colorHUE >= 103 && colorHUE <= 115){colorSensor = 3;}else{colorSensor = 1;}
	}else{colorSensor = 2;}

	return colorSensor;
}

int colorRGBSensorDerecho(tSensors sDerecho, int colorDerecho){

	int colorSensor = 2;
	int colorHUE = 0;
	int tiempoLectura = 700;

	if(colorDerecho < 35 ){
		while(tiempoLectura > -1){colorHUE = getColorHue(sDerecho); tiempoLectura--;}
		if(colorHUE >= 162 && colorHUE <= 174){colorSensor = 3;}else{colorSensor = 1;}
	}else{colorSensor = 2;}


	return colorSensor;

}
//-----------------------------------------------------------PROGRAMA-PRINCIPAL-------------------------------------------------------------
/*
#define   DATALOG_SERIES_0    0
#define   DATALOG_SERIES_1    1
#define   DATALOG_SERIES_2    2
*/
task main(){

	int colorIzq = 0;
	int colorDer = 0;
	int colorIzqRGB = 0;
	int colorDerRGB = 0;
	int cIzqReflected = 0;
	int cDerReflected = 0;
	int cCenReflected = 0;

	while (true)
	{
		cIzqReflected = SensorValue[S1];
		cDerReflected = SensorValue[S2];
		cCenReflected = SensorValue[S3];
		/*
		datalogDataGroupStart();
		datalogAddValue( DATALOG_SERIES_0, cIzqReflected );
		datalogAddValue( DATALOG_SERIES_1, cDerReflected );
		datalogAddValue( DATALOG_SERIES_2, cCenReflected );
		datalogDataGroupEnd();
		*/
		seguidorLineaNegra(cIzqReflected, cDerReflected);

		colorIzq = colorSensorIzquierdo(sensorIzquierdo, cIzqReflected);
		colorDer = colorSensorDerecho(sensorDerecho, cDerReflected);

		if(colorIzq == 2 || colorDer == 2){

			if(colorIzq == 2){

				displayCenteredBigTextLine(3,"POS VERDE IZQ");
				forward(0.05, rotations, 15);
				stopMultipleMotors(motorDerecho, motorIzquierdo);
				colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo, cIzqReflected);
				if(colorIzqRGB == 1 || colorIzqRGB == 2){
					if(colorIzqRGB == 1){
						setMotorSpeed(motorDerecho, velocidadAvance);
						setMotorSpeed(motorIzquierdo, velocidadRetroceso);
						sleep(250);
						}else{
						setMotorSpeed(motorDerecho, velocidadRetroceso);
						setMotorSpeed(motorIzquierdo, velocidadAvance);
						sleep(250);
					}

					}else{

					stopMultipleMotors(motorDerecho, motorIzquierdo);
					colorDerRGB = colorRGBSensorDerecho(sensorDerecho, cDerReflected);
					if(colorDerRGB == 3){
						forward(0.3, rotations, velocidadAvance);
						turnLeft(2.5, rotations, velocidadAvance);
						forward(0.5, rotations, velocidadAvance);
						}else{
						forward(0.3, rotations, velocidadAvance);
						turnLeft(0.9, rotations, velocidadAvance);
						forward(0.3, rotations, velocidadAvance);
					}

				}

				}else{

				displayCenteredBigTextLine(3,"POS VERDE DER");
				forward(0.05, rotations, 15);
				stopMultipleMotors(motorDerecho, motorIzquierdo);
				colorDerRGB = colorRGBSensorIzquierdo(sensorDerecho, cDerReflected);
				if(colorDerRGB == 1 || colorDerRGB == 2){
					if(colorDerRGB == 1){
						setMotorSpeed(motorDerecho, velocidadRetroceso);
						setMotorSpeed(motorIzquierdo, velocidadAvance);
						sleep(250);
						}else{
						setMotorSpeed(motorDerecho, velocidadAvance);
						setMotorSpeed(motorIzquierdo, velocidadRetroceso);
						sleep(250);
					}
					}else{

					stopMultipleMotors(motorDerecho, motorIzquierdo);
					colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo, cIzqReflected);
					if(colorIzqRGB == 3){
						forward(0.3, rotations, 15);
						turnRight(2.5, rotations, 15);
						forward(0.5, rotations, 15);
						}else{
						forward(0.3, rotations, 15);
						turnRight(0.9, rotations, 15);
						forward(0.3, rotations, 15);
					}

				}

			}

		}

	}

}
