#pragma config(Sensor, S1,     sensorIzquierdo, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorDerecho,  sensorEV3_Color)
#pragma config(Sensor, S3,     sensorCentro,   sensorEV3_Color)
#pragma config(Motor,  motorA,          motorIzquierdo, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorDerecho,  tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   DATALOG_SERIES_0    0
#define   DATALOG_SERIES_1    1

int colorSensorIzquierdo(tSensors sIzquierdo){

	int colorIzquierdo = 0;
	int colorBlanco = 0;

	colorIzquierdo = getColorReflected(sIzquierdo);

	//PREGUNTA SI EL SENSOR IZQUIERDO ESTA EN EL BLANCO
	//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO
	//COMO VALOR SUPERIOR AL 27
	if(colorIzquierdo > 20)												{colorBlanco = 0;} 		//SE RETORNA 0 -> COLOR BLANCO;
	if(colorIzquierdo >= 6 && colorIzquierdo <= 10){colorBlanco = 2;}	  //SE RETORNA 2 -> COLOR POSIBLE VERDE;
	if(colorIzquierdo >= 1 && colorIzquierdo <= 5){colorBlanco = 1;}		//SE RETORNA 1 -> COLOR NEGRO

	return colorBlanco;
}

int colorSensorDerecho(tSensors sDerecho){

	int colorDerecho = 0;
	int colorBlanco = 0;


	colorDerecho = getColorReflected(sDerecho);

	//PREGUNTA SI EL SENSOR DERECHO ESTA EN EL BLANCO
	//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO
	//COMO VALOR SUPERIOR AL 45
	if(colorDerecho > 27)                      {colorBlanco = 0;}        //SE RETORNA 0 -> COLOR BLANCO;
	if(colorDerecho >= 5 && colorDerecho <= 10){colorBlanco = 2;}        //SE RETORNA 2 -> COLOR POSIBLE VERDE <= 7
	if(colorDerecho >= 2 && colorDerecho <= 4) {colorBlanco = 1;}        //SE RETORNA 1 -> COLOR NEGRO; <= 6


	return colorBlanco;
}

int colorRGBSensorIzquierdo(tSensors sIzquierdo){

	int colorSensor = 2;
	int colorHUE = 0;
	int tiempoLectura = 500;

	if(getColorReflected(sIzquierdo) < 20){
		while(tiempoLectura > -1){colorHUE = getColorHue(sIzquierdo); tiempoLectura--;}
		if(colorHUE >= 105 && colorHUE <= 115){colorSensor = 3;}else{colorSensor = 1;}
	}else{colorSensor = 2;}

	return colorSensor;
}

int colorRGBSensorDerecho(tSensors sDerecho){

	int colorSensor = 2;
	int colorHUE = 0;
	int tiempoLectura = 500;

	if(getColorReflected(sDerecho) < 27 ){
		while(tiempoLectura > -1){colorHUE = getColorHue(sDerecho); tiempoLectura--;}
		if(colorHUE >= 165 && colorHUE <= 175){colorSensor = 3;}else{colorSensor = 1;}
	}else{colorSensor = 2;}


	return colorSensor;

}

task main(){

	int velocidadAvance = 20;
	int minMotorSpeed = -20;
	int colorIzq = 0;
	int colorDer = 0;
	int colorIzqRGB = 0;
	int colorDerRGB = 0;
	int controlLineaNegra = 0;
	int colorIzqReflected = 0;
	int colorDerReflected = 0;
	int colorCenReflected = 0;
	int contadorPosVerde = 3;

	datalogClear();

	while (true)
	{
	seguidorLinea:
		colorIzqReflected = getColorReflected(sensorIzquierdo);
		colorDerReflected = getColorReflected(sensorDerecho);
		colorCenReflected = getColorReflected(sensorCentro);

		datalogDataGroupStart();
		datalogAddValue( DATALOG_SERIES_0, colorIzqReflected );
		datalogAddValue( DATALOG_SERIES_1, colorDerReflected );
		datalogDataGroupEnd();


		while(colorIzqReflected <= 20 && colorCenReflected <= 47){
			//setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, 0);
			//sleep(3000);
			displayCenteredBigTextLine(3,"NEGRO FALSO IZQ");
			//forward(0.7, rotations, velocidadAvance);
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
			sleep(750);
			goto seguidorLinea;
			//setMotorSpeed(motorDerecho, velocidadAvance);
			//setMotorSpeed(motorIzquierdo, velocidadAvance);
		}

		while(colorDerReflected <= 27 && colorCenReflected <= 47){
			//setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, 0);
			//sleep(3000);
			displayCenteredBigTextLine(3,"NEGRO FALSO DER");
			//forward(0.7, rotations, velocidadAvance);
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 0, velocidadAvance);
			sleep(750);
			goto seguidorLinea;
			//setMotorSpeed(motorDerecho, velocidadAvance);
			//setMotorSpeed(motorIzquierdo, velocidadAvance);
		}

		controlLineaNegra = round((((colorIzqReflected - colorDerReflected)/2)+8)*2.2/15);

		if(controlLineaNegra >= 4){controlLineaNegra = 3;}
		if(controlLineaNegra <= -4){controlLineaNegra = -3;}

		switch (controlLineaNegra)
		{
		case 3:
			setMotorSpeed(motorIzquierdo, velocidadAvance*1.8);
			setMotorSpeed(motorDerecho, minMotorSpeed*2.2);
			break;
		case 2:
			setMotorSpeed(motorIzquierdo, velocidadAvance*1.3);
			setMotorSpeed(motorDerecho, velocidadAvance/-1.7);
			break;
		case 1:
			setMotorSpeed(motorIzquierdo, velocidadAvance*1.2);
			setMotorSpeed(motorDerecho, velocidadAvance/-1.2);
			break;
		case 0:
			setMotorSpeed(motorIzquierdo, velocidadAvance);
			setMotorSpeed(motorDerecho, velocidadAvance);
			break;
		case -1:
			setMotorSpeed(motorIzquierdo, velocidadAvance/-1.2);
			setMotorSpeed(motorDerecho, velocidadAvance*1.2);
			break;
		case -2:
			setMotorSpeed(motorIzquierdo, velocidadAvance/-1.7);
			setMotorSpeed(motorDerecho, velocidadAvance*1.3);
			break;
		case -3:
			setMotorSpeed(motorIzquierdo, minMotorSpeed*2.2);
			setMotorSpeed(motorDerecho, velocidadAvance*1.8);
			break;
		}
		colorIzq = colorSensorIzquierdo(sensorIzquierdo);
		colorDer = colorSensorDerecho(sensorDerecho);

		if (colorIzq  == 2 ||  colorDer == 2)
		{

			if(colorIzq == 2){      //COMPROBACION DE VERDE
				displayCenteredBigTextLine(3,"POS VERDE IZQ");
				stopMultipleMotors(motorDerecho, motorIzquierdo);  //FRENA EL ROBOT
			verificarVerdeIzq:
				forward(0.05, rotations, velocidadAvance); //AVANZA
				colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo);//COMPRUEBA SI EL SENSOR IZQUIERDO ESTA SOBRE EL VERDE
				displayCenteredBigTextLine(3,"colorIzq %d",colorIzqRGB);
				if(colorIzqRGB == 1 || colorIzqRGB == 2){
					//contadorPosVerde--;
					backward(0.1, rotations, velocidadAvance);
					goto seguidorLinea;
				}
				/*
				if(contadorPosVerde == 0){
				contadorPosVerde = 3;
				goto seguidorLinea;
				}
				*/
				if(colorIzqRGB == 3){
					stopMultipleMotors(motorDerecho, motorIzquierdo);//FRENO EL ROBOT
					colorDerRGB = colorRGBSensorDerecho(sensorDerecho);//GUARDA EL RGB EN LA VARIABLE colorDerRGB
					if(colorDerRGB == 3){//VERIFICA SI TAMBIEN EL SENSOR DERECHO ESTA SOBRE EL VERDE
						displayCenteredBigTextLine(3,"DOBLE VERDE");//SI LA CONDICION ES VERDADERA ENTONCES ES DOBLE VERDE
						forward(0.3, rotations, velocidadAvance);
						turnLeft(2.5, rotations, velocidadAvance);
						forward(0.5, rotations, velocidadAvance);
						}else{
						//SINO SE GIRA HACIA LA IZQUIERDA
						displayCenteredBigTextLine(3,"VERDE IZQ");
						forward(0.3, rotations, velocidadAvance);
						turnLeft(1.1, rotations, velocidadAvance);
						forward(0.3, rotations, velocidadAvance);
					}
					}else{
					backward(0.14, rotations, velocidadAvance);
				}
			}

			if(colorDer == 2){ //COMPROBACION DE VERDE
				displayCenteredBigTextLine(3,"POS VERDE DER");
				stopMultipleMotors(motorDerecho, motorIzquierdo);  //FRENA EL ROBOT
			verificarVerdeDer:
				forward(0.05, rotations, velocidadAvance); //AVANZA
				colorDerRGB = colorRGBSensorDerecho(sensorDerecho);
				displayCenteredBigTextLine(3,"colorDer %d",colorDerRGB);
				if(colorDerRGB == 1 || colorDerRGB == 2){
					//contadorPosVerde--;
					backward(0.1, rotations, velocidadAvance);
					goto seguidorLinea;
				}
				/*
				if(contadorPosVerde == 0){
				contadorPosVerde = 3;
				goto seguidorLinea;
				}
				*/
				/*
				if(colorIzqRGB == 1 && contadorPosVerde > 0){
				contadorPosVerde--;
				goto verificarVerdeDer;
				backward(0.1, rotations, velocidadAvance);
				}
				if(contadorPosVerde == 0){
				contadorPosVerde = 3;
				goto seguidorLinea;
				}
				*/
				//COMPRUEBA SI EL SENSOR DERECHO ESTA SOBRE EL VERDE
				if(colorDerRGB == 3){
					stopMultipleMotors(motorDerecho, motorIzquierdo);//FRENO EL ROBOT
					colorIzqRGB = colorRGBSensorIzquierdo(sensorIzquierdo);	//GUARDA EL RGB EN LA VARIABLE colorIzqRGB
					if(colorIzqRGB == 3){	//VERIFICA SI TAMBIEN EL SENSOR IZQUIERDO ESTA SOBRE EL VERDE
						displayCenteredBigTextLine(3,"DOBLE VERDE");//SI LA CONDICION ES VERDADERA ENTONCES ES DOBLE VERDE
						forward(0.3, rotations, velocidadAvance);
						turnRight(2.5, rotations, velocidadAvance);
						forward(0.5, rotations, velocidadAvance);
						}else{
						//SINO SE GIRA HACIA LA DERECHA
						displayCenteredBigTextLine(3,"VERDE DER");
						forward(0.3, rotations, velocidadAvance);
						turnRight(1.12, rotations, velocidadAvance);
						forward(0.3, rotations, velocidadAvance);
					}
					}else{
					backward(0.14, rotations, velocidadAvance);
				}
			}

		}

	}

}
