#pragma config(Sensor, S1,     sensorIzquierdo, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorDerecho,  sensorEV3_Color)
#pragma config(Motor,  motorA,          motorIzquierdo, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorDerecho,  tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int colorSensorIzquierdo(tSensors sIzquierdo){

	int colorIzquierdo = 0;
	int colorBlanco = 0;

	colorIzquierdo = getColorReflected(sIzquierdo);

	//PREGUNTA SI EL SENSOR IZQUIERDO ESTA EN EL BLANCO
	if(colorIzquierdo > 30){ //SE TOMA COMO VALOR DE REFERENCIA EN BLANCO COMO VALOR SUPERIOR AL 30
		colorBlanco = 1;//SE RETORNA 1 -> COLOR BLANCO;
		}else{
		colorBlanco = 0;//SE RETORNA 0 -> COLOR NEGRO;
	}
	return colorBlanco;
}

int colorSensorDerecho(tSensors sDerecho){

	int colorDerecho = 0;
	int colorBlanco = 0;

	colorDerecho = getColorReflected(sDerecho);

	//PREGUNTA SI EL SENSOR DERECHO ESTA EN EL BLANCO
	if(colorDerecho > 30){//SE TOMA COMO VALOR DE REFERENCIA EN BLANCO COMO VALOR SUPERIOR AL 30
		colorBlanco = 1;//SE RETORNA 1 -> COLOR BLANCO;
		}else{
		colorBlanco = 0;//SE RETORNA 0 -> COLOR NEGRO;
	}
	return colorBlanco;
}
/*
int colorRGBSensorIzquierdo(tSensors sIzquierdo){

	//VARIABLES DE CONTROL
	int colorSensor,redChannel,greenChannel,blueChannel = 0;
	//FUNCION QUE GUARDA LOS VALORES RGB EN LAS VARIABLES redChannel - greenChannel - blueChannel
	getColorRGB(sIzquierdo, redChannel, greenChannel, blueChannel);

	//VERIFICA SI LAS VARIABLES TIENEN EL VALOR ESPECIFICADO EN EL RANGO
	//DE VALORES RGB ESPECIFICO PARA CADA COLOR (NEGRO, BLANCO, VERDE)

	if((redChannel >= 7 && redChannel <= 8) && (greenChannel >= 7 && greenChannel <= 8) && (blueChannel >= 10 && blueChannel <= 12)){
		colorSensor = 1;//COLOR NEGRO
	}

	if((redChannel >= 59 && redChannel <= 61) && (greenChannel >= 53 && greenChannel <= 55) && (blueChannel >= 68 && blueChannel <= 71)){
		colorSensor = 2;//COLOR BLANCO
	}

	if((redChannel >= 8 && redChannel <= 9) && (greenChannel >= 28 && greenChannel <= 30) && (blueChannel >= 26 && blueChannel <= 28)){
		colorSensor = 3;//COLOR VERDE
	}

	return colorSensor;

}

int colorRGBSensorDerecho(tSensors sDerecho){

	//VARIABLES DE CONTROL
	int colorSensor,redChannel,greenChannel,blueChannel = 0;
	//FUNCION QUE GUARDA LOS VALORES RGB EN LAS VARIABLES redChannel - greenChannel - blueChannel
	getColorRGB(sDerecho, redChannel, greenChannel, blueChannel);

	//VERIFICA SI LAS VARIABLES TIENEN EL VALOR ESPECIFICADO EN EL RANGO
	//DE VALORES RGB ESPECIFICO PARA CADA COLOR (NEGRO, BLANCO, VERDE)

	if((redChannel >= 7 && redChannel <= 8) && (greenChannel >= 8 && greenChannel <= 10) && (blueChannel >= 1 && blueChannel <= 3)){
		colorSensor = 1;//COLOR NEGRO
	}

	if((redChannel >= 51 && redChannel <= 53) && (greenChannel >= 56 && greenChannel <= 58) && (blueChannel >= 30 && blueChannel <= 32)){
		colorSensor = 2;//COLOR BLANCO
	}

	if((redChannel >= 8 && redChannel <= 10) && (greenChannel >= 32 && greenChannel <= 35) && (blueChannel >= 8 && blueChannel <= 9)){
		colorSensor = 3;//COLOR VERDE
	}

	return colorSensor;

}
*/
task main()
{
	int velocidadAvance = 30;
	int velocidadRetroceso = -30;
	int colorIzq = 0;
	int colorDer = 0;

	while(true){

		colorIzq = colorSensorIzquierdo(sensorIzquierdo);
		colorDer = colorSensorDerecho(sensorDerecho);

		if(colorIzq == 1 && colorDer == 1){
			setMotorSpeed(motorIzquierdo, velocidadAvance);
			setMotorSpeed(motorDerecho, velocidadAvance);
		}

		if(colorIzq == 0 && colorDer == 0){
			//setMotorSpeed(motorIzquierdo, velocidadRetroceso);
			//setMotorSpeed(motorDerecho, velocidadRetroceso);
			setMotorSyncTime(motorIzquierdo, motorDerecho, 0, 1000, velocidadAvance);
		}

		if(colorIzq == 0 && colorDer == 1){
			setMotorSpeed(motorIzquierdo, velocidadRetroceso);
			setMotorSpeed(motorDerecho, 0);
		}

		if(colorIzq == 1 && colorDer == 0){
			setMotorSpeed(motorIzquierdo, 0);
			setMotorSpeed(motorDerecho, velocidadRetroceso);
		}

	}

}
