

#pragma config(Sensor, S2,     sen2,           sensorEV3_Color)
#pragma config(Sensor, S3,     sen3,           sensorEV3_Color)
#pragma config(Motor,  motorB,          MB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int sen2 = 0;
int sen3 = 0;
while (true){
sen2 = getColorReflected (S2);
sen3 = getColorReflected (S3);

/*c 2 ,b3*/
if (sen2 <35 ){
	setMotorSpeed (MC,20);
}
else {
	setMotorSpeed (MC,-20);
}

if (sen3 <35 ){
	setMotorSpeed (MB,-20);
}
else {
	setMotorSpeed (MB,20);
}

}



}
