#pragma config(Sensor, S1,     Sen1,           sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Target= 0;
	int TurnMultiplier= 1;
	int Motors= 0;
	int LS1=
	int LS2=
	int LS3=
	int LS4=
	int LS5=
	int LS6=
	int LS7=
	int LS8=
	while (true){

		Motors= (((

	}
