#pragma config(Sensor, S1,     SI,             sensorEV3_Color)
#pragma config(Sensor, S2,     SD,             sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int GI = 0;
	int RI = 0;
	int BI = 0;
	int GD = 0;
	int RD = 0;
	int BD = 0;
	while(true){
		getColorRGB(SI, RI, GI, BI);
		getColorRGB(SD, RD, GD, BD);

		displayCenteredBigTextLine ( 2 ,  "SenIzq %d,%d,%d", RI ,GI ,BI );
		displayCenteredBigTextLine ( 5 ,  "SenDer %d,%d,%d", RD ,GD ,BD );
	}

}
